const JobDiscription = [
  {
    img: "src/assets/Amazon.png",
    isSave: "Save",
    saveImg: "src/assets/Save.png",
    companyName: "Amazon",
    time: "5 days ago",
    Description: "Senior UI/UX Designer",
    jobTime: "Part-Time",
    jobType: "Senior Level",
    salary: "$120/hr",
    loc: "Mumbai, India",
  },
  {
    img: "src/assets/Google Logo.png",
    isSave: "Saved",
    saveImg: "src/assets/Saved.png",
    companyName: "Google",
    time: "30 days ago",
    Description: "Graphic Designer",
    jobTime: "Part-Time",
    jobType: "Flexible Schedule",
    salary: "$150-220k",
    loc: "Kochi, India",
  },
  {
    img: "src/assets/Dribble Logo.png",
    isSave: "Save",
    saveImg: "src/assets/Save.png",
    companyName: "Dribble",
    time: "18 days ago",
    Description: "Senior Motion Designer",
    jobTime: "Contract",
    jobType: "Remote",
    salary: "$85/hr",
    loc: "Chennai, India",
  },
  {
    img: "src/assets/Figma Logo.png",
    isSave: "Saved",
    saveImg: "src/assets/Saved.png",
    companyName: "Figma",
    time: "5 days ago",
    Description: "UX Designer",
    jobTime: "Full-Time",
    jobType: "In office",
    salary: "$200-250k",
    loc: "Bangalore, India",
  },
  {
    img: "src/assets/Aribnb Logo.png",
    isSave: "Save",
    saveImg: "src/assets/Save.png",
    companyName: "Airbnb",
    time: "5 days ago",
    Description: "Junior UI/UX Designer",
    jobTime: "Contract",
    jobType: "Remote",
    salary: "$100/hr",
    loc: "Delhi, India",
  },
  {
    img: "src/assets/Apple Logo.png",
    isSave: "Saved",
    saveImg: "src/assets/Saved.png",
    companyName: "Apple",
    time: "5 days ago",
    Description: "Graphics Designer",
    jobTime: "Full-Time",
    jobType: "Flexible Schedule",
    salary: "$85-120k",
    loc: "Kerala, India",
  },
  {
  img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRiUX9GhKN31-SvsRc2dXF9cZ6FndxQhKlfFUNQtZCuHA&s=10",
  isSave: "Save",
  saveImg: "src/assets/Save.png",
  companyName: "Microsoft",
  time: "2 days ago",
  Description: "Frontend Developer",
  jobTime: "Full-Time",
  jobType: "Hybrid",
  salary: "$140-180k",
  loc: "Hyderabad, India",
},
{
  img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSHh0J_X-VhgQCxTcUGSr18TgkmIayVgODIh9XfS357HQ&s=10",
  isSave: "Saved",
  saveImg: "src/assets/Saved.png",
  companyName: "Netflix",
  time: "1 week ago",
  Description: "Product Designer",
  jobTime: "Full-Time",
  jobType: "Remote",
  salary: "$180-220k",
  loc: "Pune, India",
},
{
  img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRXn1gWoEgC9YuqyhP1aohyhV0nOdYcTef-sNEb5mx4yw&s=10",
  isSave: "Save",
  saveImg: "src/assets/Save.png",
  companyName: "Adobe",
  time: "4 days ago",
  Description: "UI Designer",
  jobTime: "Full-Time",
  jobType: "Hybrid",
  salary: "$110-150k",
  loc: "Noida, India",
},
{
  img: "https://static.vecteezy.com/system/resources/previews/055/331/308/non_2x/circle-spotify-icon-logo-symbol-free-png.png",
  isSave: "Saved",
  saveImg: "src/assets/Saved.png",
  companyName: "Spotify",
  time: "10 days ago",
  Description: "Visual Designer",
  jobTime: "Contract",
  jobType: "Remote",
  salary: "$95/hr",
  loc: "Remote",
},
{
  img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSoZzfJuVmvqQwMBkD6gxYNqe8d-v7lE5hUp7CMrHi9ig&s=10",
  isSave: "Save",
  saveImg: "src/assets/Save.png",
  companyName: "Meta",
  time: "3 days ago",
  Description: "React Developer",
  jobTime: "Full-Time",
  jobType: "Hybrid",
  salary: "$170-210k",
  loc: "Gurgaon, India",
},
{
  img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS9SBqfDBIfMZMTgonkSZNlev6mcVMo-M7xTMFQNgv33A&s=10",
  isSave: "Saved",
  saveImg: "src/assets/Saved.png",
  companyName: "Uber",
  time: "6 days ago",
  Description: "Mobile App Designer",
  jobTime: "Part-Time",
  jobType: "Flexible Schedule",
  salary: "$100/hr",
  loc: "Bangalore, India",
}
];

export default JobDiscription;